# Generated by Django 5.0.1 on 2025-11-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_has_full_account',
            field=models.BooleanField(db_column='User_has_full_account', default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_email',
            field=models.EmailField(blank=True, db_column='User_email', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id_number',
            field=models.CharField(db_column='User_id_number', default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
