# Generated by Django 5.0.1 on 2025-11-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_user_has_full_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_has_full_account',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_is_registered',
            field=models.BooleanField(db_column='User_is_registered', default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_email',
            field=models.EmailField(db_column='User_email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id_number',
            field=models.CharField(blank=True, db_column='User_id_number', max_length=20, null=True, unique=True),
        ),
    ]
