# Generated by Django 5.0.1 on 2025-11-18 05:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_user_has_full_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrequest',
            name='verification_request_land_record_id',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='verification_request_requested_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_authenticity_score',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_verified_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_verified_by',
        ),
        migrations.RemoveField(
            model_name='legalcasesubmission',
            name='case_evidence_document',
        ),
        migrations.AlterField(
            model_name='legalcasesubmission',
            name='case_created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='Legal_case_created_at'),
        ),
        migrations.AlterField(
            model_name='legalcasesubmission',
            name='case_description',
            field=models.TextField(db_column='Legal_case_description'),
        ),
        migrations.AlterField(
            model_name='legalcasesubmission',
            name='case_id',
            field=models.UUIDField(db_column='Legal_case_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='legalcasesubmission',
            name='case_land_officer_notes',
            field=models.TextField(blank=True, db_column='Legal_case_land_officer_notes', null=True),
        ),
        migrations.AlterField(
            model_name='legalcasesubmission',
            name='case_land_record',
            field=models.ForeignKey(db_column='Legal_case_land_record_id', on_delete=django.db.models.deletion.CASCADE, related_name='legal_cases', to='core.landrecord'),
        ),
        migrations.AlterField(
            model_name='legalcasesubmission',
            name='case_legal_officer',
            field=models.ForeignKey(db_column='Legal_case_legal_officer_id', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legalcasesubmission',
            name='case_priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_column='Legal_case_priority', default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='legalcasesubmission',
            name='case_status',
            field=models.CharField(choices=[('submitted', 'Submitted to Land Officer'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_column='Legal_case_status', default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='legalcasesubmission',
            name='case_title',
            field=models.CharField(db_column='Legal_case_title', max_length=255),
        ),
        migrations.AlterField(
            model_name='legalcasesubmission',
            name='case_type',
            field=models.CharField(choices=[('dispute', 'Boundary Dispute'), ('inheritance', 'Inheritance Dispute'), ('fraud', 'Fraud Case'), ('multiple_claim', 'Multiple Ownership Claim'), ('encroachment', 'Encroachment'), ('other', 'Other')], db_column='Legal_case_type', max_length=50),
        ),
        migrations.AlterField(
            model_name='legalcasesubmission',
            name='case_updated_at',
            field=models.DateTimeField(auto_now=True, db_column='Legal_case_updated_at'),
        ),
        migrations.AlterField(
            model_name='ownershiphistory',
            name='history_deed_number_new',
            field=models.CharField(db_column='Ownership_history_new_deed_number', max_length=100),
        ),
        migrations.AlterField(
            model_name='ownershiphistory',
            name='history_deed_number_old',
            field=models.CharField(db_column='Ownership_history_old_deed_number', max_length=100),
        ),
        migrations.AlterField(
            model_name='ownershiphistory',
            name='history_id',
            field=models.UUIDField(db_column='Ownership_history_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ownershiphistory',
            name='history_land_record',
            field=models.ForeignKey(db_column='Ownership_history_land_record_id', on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='core.landrecord'),
        ),
        migrations.AlterField(
            model_name='ownershiphistory',
            name='history_new_owner',
            field=models.ForeignKey(db_column='Ownership_history_new_owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownershiphistory',
            name='history_notes',
            field=models.TextField(blank=True, db_column='Ownership_history_notes', null=True),
        ),
        migrations.AlterField(
            model_name='ownershiphistory',
            name='history_previous_owner',
            field=models.ForeignKey(db_column='Ownership_history_previous_owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownershiphistory',
            name='history_transaction',
            field=models.ForeignKey(blank=True, db_column='Ownership_history_transaction_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownership_changes', to='core.transaction'),
        ),
        migrations.AlterField(
            model_name='ownershiphistory',
            name='history_transfer_date',
            field=models.DateTimeField(auto_now_add=True, db_column='Ownership_history_transfer_date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(db_column='User_is_staff', default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(db_column='User_is_superuser', default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(db_column='User_password', max_length=128),
        ),
        migrations.AlterModelTable(
            name='legalcasesubmission',
            table='Legal_case',
        ),
        migrations.DeleteModel(
            name='OcrRecord',
        ),
        migrations.DeleteModel(
            name='VerificationRequest',
        ),
    ]
