# Generated by Django 5.0.1 on 2025-12-13 12:31

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_userprofile_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrecord',
            name='land_records_first_registration_date',
            field=models.DateTimeField(auto_now_add=True, db_column='Land_records_first_registration_date', default=timezone.now),
            preserve_default=False,
        ),
    ]
