# Generated by Django 5.0.1 on 2025-12-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_landrecord_land_records_first_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownershiphistory',
            name='history_transfer_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('transfer', 'Transfer'), ('inheritance', 'Inheritance'), ('gift', 'Gift')], db_column='Ownership_history_transfer_type', max_length=20),
        ),
    ]
