# Generated by Django 5.0.1 on 2025-12-20 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_ownershiphistory_history_transfer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_is_active',
            new_name='is_active',
        ),
    ]
