# Generated by Django 5.0.1 on 2026-05-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_user_is_active_userprofile_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_active',
            new_name='user_is_active',
        ),
    ]
